In [1]:
import pandas as pd
from dont_patronize_me import DontPatronizeMe
device = 'cuda'

In [2]:
dpm = DontPatronizeMe('.')
# This method loads the subtask 1 data
dpm.load_task1()
# which we can then access as a dataframe
dataset = dpm.train_task1_df
dataset.head()

,par_id,art_id,keyword,country,text,label,orig_label
0,1,@@24942188,hopeless,ph,"we 're living in times of absolute insanity , ...",0,0
1,2,@@21968160,migrant,gh,"in libya today , there are countless number of...",0,0
2,3,@@16584954,immigrant,ie,"""white house press secretary sean spicer said ...",0,0
3,4,@@7811231,disabled,nz,council customers only signs would be displaye...,0,0
4,5,@@1494111,refugee,ca,""""""" just like we received migrants fleeing el ...",0,0

### Training and Validation datasets generation for Codalab practice

In [46]:
'''
training_codalab = pd.read_csv('train_semeval_parids-labels.csv')
validation_codalab = pd.read_csv('dev_semeval_parids-labels.csv')

training_codalab.par_id = training_codalab.par_id.astype(str)
validation_codalab.par_id = validation_codalab.par_id.astype(str)

train = [] # will contain par_id, label and text
for idx in range(len(training_codalab)):  
  parid = training_codalab.par_id[idx]
  # select row from original dataset to retrieve `text` and binary label
  text = dataset.loc[dataset.par_id == parid].text.values[0]
  label = dataset.loc[dataset.par_id == parid].label.values[0]
  train.append({
      'par_id':parid,
      'text':text,
      'label':label
  })

validation = [] # will contain par_id, label and text
for idx in range(len(validation_codalab)):  
  parid = validation_codalab.par_id[idx]
  # select row from original dataset to retrieve `text` and binary label
  text = dataset.loc[dataset.par_id == parid].text.values[0]
  label = dataset.loc[dataset.par_id == parid].label.values[0]
  validation.append({
      'par_id':parid,
      'text':text,
      'label':label
  })
train = pd.DataFrame(train)
validation = pd.DataFrame(validation)

train.to_csv("train_subset.csv", index = False)
validation.to_csv("validation_subset.csv", index = False)'''